services:
  devbox:
    image: healthsamurai/aidboxone:latest
    depends_on:
      - devbox-db
    links:
      - devbox-db:database
    env_file:
      - .env.aidbox
      - env_tests
    environment:
      AIDBOX_LICENSE: ${TESTS_AIDBOX_LICENSE}
    ports:
      - 8080:8080
  devbox-db:
    image: healthsamurai/aidboxdb:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbox
  devbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - devbox
    depends_on:
      - devbox
    healthcheck:
      test: curl --fail http://devbox:8080/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
