version: '3.1'
services:
  devbox:
    image: healthsamurai/devbox:edge
    command: ["wait-for-it.sh", "database:5432", "--strict", "--timeout=0", "--", "java", "-jar", "/aidbox.jar", "-m", "devbox.core"]
    depends_on:
      - devbox-db
    links:
      - devbox-db:database
    env_file:
      - env_tests
    environment:
      AIDBOX_LICENSE_ID: ${TESTS_AIDBOX_LICENSE_ID}
      AIDBOX_LICENSE_KEY: ${TESTS_AIDBOX_LICENSE_KEY}
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh:cached
    ports:
    - 8080:8080
  devbox-db:
    image: healthsamurai/aidboxdb:13.2
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
