[tool.black]
line-length = 100
target-version = ['py39']
exclude = '''
(
  /(
    | \.git
    | \.pytest_cache
    | htmlcov
    | locales
    | resources
    | requirements
    | embed
  )/
)
'''

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_first_party = ["testscript"]
