name: Publish to https://pypi.org/ and dockerhub
on:
  release:
    types: [created]

jobs:
  pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install wheel and build
        run: pip install wheel build
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
  dockerhub:
    runs-on: ubuntu-latest
    needs: pypi
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Extract tag
        shell: bash
        run: >-
          pip install testscript-eval &&
          echo "import testscript_eval;print(f'tag={testscript_eval.VERSION}')" | python >>$GITHUB_OUTPUT
        id: extract_tag
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: docker run --rm --privileged tonistiigi/binfmt --install all
      - run: >-
          docker buildx build
          --platform linux/arm64,linux/amd64
          --push
          --tag bedasoftware/testscript-eval:${{ steps.extract_tag.outputs.tag }}
          --tag bedasoftware/testscript-eval:latest
          .
